CREATE TABLE companies(
  ID SERIAL PRIMARY KEY NOT NULL,
  NAME       TEXT,
  BRANCHE TEXT,
  STREET TEXT,
  PLZ VARCHAR(10),
  CITY TEXT,
  PHONENUMBER TEXT,
  WEBSITE TEXT ,
  EMAIL TEXT
);
CREATE EXTENSION fuzzystrmatch SCHEMA public;
