CREATE TABLE companies(
  ID SERIAL PRIMARY KEY NOT NULL,
  REF TEXT UNIQUE,
  SOURCE TEXT,
  NAME       TEXT,
  SECTOR TEXT,
  ADDRESS TEXT,
  PLZ VARCHAR(10),
  CITY TEXT,
  PHONENUMBER TEXT,
  WEBSITE TEXT ,
  EMAIL TEXT,
  create_at DATE ,
  updated_at DATE,
  LATITUDE FLOAT ,
  LONGITUDE FLOAT
);
--CREATE EXTENSION fuzzystrmatch SCHEMA public;
